/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 * 
 * @author Jakub Cachovan
 */
public class HladajRezervaciu extends javax.swing.JDialog {
    
    private String rc= "";
    /**
     * Creates new form HladajRezervaciu
     */
    public HladajRezervaciu(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * Getter pre rodné číslo cestujúceho.
     * @return 
     */
    public String getRC() {
        return rc;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelRC = new javax.swing.JLabel();
        jTextFieldRC = new javax.swing.JTextField();
        jButtonHladaj = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Vyhľadanie rezervácie");

        jLabelRC.setText("Rodné číslo");

        jTextFieldRC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldRCKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldRCKeyTyped(evt);
            }
        });

        jButtonHladaj.setText("Vyhľadaj");
        jButtonHladaj.setEnabled(false);
        jButtonHladaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHladajActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelRC)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jTextFieldRC, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonHladaj, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelRC)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldRC, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonHladaj, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Inicializácia atribútu rc a zrušenie dialogu.
     * @param evt 
     */
    private void jButtonHladajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHladajActionPerformed
        if(!"".equals(jTextFieldRC.getText())){
            rc = jTextFieldRC.getText();
            dispose();
        }else{
            JOptionPane.showMessageDialog(null, "Nebolo zadané kritérium hľadania !", "Chyba", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonHladajActionPerformed

    /**
     * Automatické kliknutie tlačidla pre vyhľadanie z poľa rodné číslo, pokial uživateľ stlačí ENTER. 
     * @param evt 
     */
    private void jTextFieldRCKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldRCKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            jButtonHladaj.doClick();
        }
        
    }//GEN-LAST:event_jTextFieldRCKeyPressed

    /**
     * Aktivovanie tlačidla pre hladanie pokial pole obsahuje text, inak je tlačidlo neaktívne.
     * @param evt 
     */
    private void jTextFieldRCKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldRCKeyTyped
        if(jTextFieldRC.getText().isEmpty()){
            jButtonHladaj.setEnabled(false);
        }else{
            jButtonHladaj.setEnabled(true);
        }
    }//GEN-LAST:event_jTextFieldRCKeyTyped

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonHladaj;
    private javax.swing.JLabel jLabelRC;
    private javax.swing.JTextField jTextFieldRC;
    // End of variables declaration//GEN-END:variables
}
