/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.Date;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import sql.sql_connect;

/**
 * Dialog pre hladanie letu.
 * @author Jakub Cachovan
 */
public final class HladajLetJDialog extends javax.swing.JDialog {
    private ResultSet rs = null;
    private Date datum;
    private String destinacia = "";
    private String dbPath;
    /**
     * Creates new form HladajLetJDialog
     * @param parent
     * @param modal
     */
    public HladajLetJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();  
        jButtonHladajLet.setIcon(new ImageIcon("./icons/search.png"));
    }

    /**
     * Setter pre adresu databázy.
     * @param dbPath 
     */
    public void setDbPath(String dbPath) {
        this.dbPath = dbPath;
    }
    
    /**
     * Naplnenie prvku combobox názvami všetkých letových destinácií.
     */
    public void naplnDestinacie(){
        try (Connection con = sql_connect.ConnectDB(this.dbPath);
                Statement state = con.createStatement();){
            rs = state.executeQuery("SELECT DISTINCT destinacia from lety");
            while(rs.next()){
                jComboBoxDestinacie.addItem(rs.getString("destinacia"));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    /**
     * Getter pre dátum odletu.
     * @return 
     */
    public Date getDatum(){
        return this.datum;  
    }
    
    /**
     * Getter pre destináciu.
     * @return 
     */
    public String getDestinacia(){
        return destinacia;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBoxDestinacie = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jCalendar1 = new com.toedter.calendar.JCalendar();
        jLabel2 = new javax.swing.JLabel();
        jButtonHladajLet = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Vyhľadanie najbližšieho letu");

        jLabel1.setText("Destinácia");

        jLabel2.setText("Dátum");

        jButtonHladajLet.setIcon(new javax.swing.ImageIcon("C:\\Users\\Acer\\Documents\\NetBeansProjects\\Letisko\\icons\\search.png")); // NOI18N
        jButtonHladajLet.setText("Hľadaj let");
        jButtonHladajLet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHladajLetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBoxDestinacie, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jCalendar1, javax.swing.GroupLayout.DEFAULT_SIZE, 338, Short.MAX_VALUE)
                    .addComponent(jButtonHladajLet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxDestinacie, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCalendar1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonHladajLet, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Inicializácia atribútov destinácia a dátum a zrušenie dialogu.
     * @param evt 
     */
    private void jButtonHladajLetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHladajLetActionPerformed
        // TODO add your handling code here:
        destinacia = jComboBoxDestinacie.getSelectedItem().toString();
        datum = new Date(jCalendar1.getDate().getTime());
        dispose();
        
    }//GEN-LAST:event_jButtonHladajLetActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonHladajLet;
    private com.toedter.calendar.JCalendar jCalendar1;
    private javax.swing.JComboBox<String> jComboBoxDestinacie;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
