/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import javax.swing.JOptionPane;
import javax.swing.JRadioButton;

/**
 *
 * @author Acer
 */
public class HladajCestDialog extends javax.swing.JDialog {

    private String meno = "";
    private String priezvisko = "";
    private String rc = "";
    /**
     * Creates new form HladajCestDialog
     */
    public HladajCestDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        jButtonHladaj.setEnabled(false);
    }

    public String getMeno() {
        return meno;
    }

    public String getPriezvisko() {
        return priezvisko;
    }

    public String getRc() {
        return rc;
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jRadioMenoPriezvisko = new javax.swing.JRadioButton();
        jRadioRC = new javax.swing.JRadioButton();
        jLabelMeno = new javax.swing.JLabel();
        jTextFieldMeno = new javax.swing.JTextField();
        jLabelPriezvisko = new javax.swing.JLabel();
        jTextFieldPriez = new javax.swing.JTextField();
        jLabelRC = new javax.swing.JLabel();
        jTextFieldRC = new javax.swing.JTextField();
        jButtonHladaj = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Vyhľadanie cestujúceho");

        buttonGroup1.add(jRadioMenoPriezvisko);
        jRadioMenoPriezvisko.setText("podľa mena a priezviska");
        jRadioMenoPriezvisko.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioMenoPriezviskoActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioRC);
        jRadioRC.setText("podľa rodného čísla");
        jRadioRC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioRCActionPerformed(evt);
            }
        });

        jLabelMeno.setText("Meno");

        jTextFieldMeno.setEnabled(false);

        jLabelPriezvisko.setText("Priezvisko");

        jTextFieldPriez.setEnabled(false);

        jLabelRC.setText("Rodné číslo");

        jTextFieldRC.setEnabled(false);

        jButtonHladaj.setText("Vyhľadaj");
        jButtonHladaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHladajActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldMeno)
                    .addComponent(jTextFieldPriez)
                    .addComponent(jTextFieldRC)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jRadioMenoPriezvisko)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioRC))
                            .addComponent(jLabelMeno)
                            .addComponent(jLabelPriezvisko)
                            .addComponent(jLabelRC))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jButtonHladaj, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioMenoPriezvisko)
                    .addComponent(jRadioRC))
                .addGap(18, 18, 18)
                .addComponent(jLabelMeno)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldMeno, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelPriezvisko)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldPriez, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelRC)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldRC, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonHladaj, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioMenoPriezviskoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioMenoPriezviskoActionPerformed
        // TODO add your handling code here:
        jTextFieldMeno.setEnabled(true);
        jTextFieldPriez.setEnabled(true);
        jTextFieldRC.setEnabled(false);
        jButtonHladaj.setEnabled(true);
        
        
    }//GEN-LAST:event_jRadioMenoPriezviskoActionPerformed

    private void jRadioRCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioRCActionPerformed
        // TODO add your handling code here:
        jTextFieldMeno.setEnabled(false);
        jTextFieldPriez.setEnabled(false);
        jTextFieldRC.setEnabled(true);
        jButtonHladaj.setEnabled(true);
    }//GEN-LAST:event_jRadioRCActionPerformed

    private void jButtonHladajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHladajActionPerformed
        // TODO add your handling code here:
        
        if(jRadioMenoPriezvisko.isSelected()){
            meno = jTextFieldMeno.getText();
            priezvisko = jTextFieldPriez.getText();
        }else if(jRadioRC.isSelected()){
            rc = jTextFieldRC.getText();
        }    
        if(rc.equalsIgnoreCase("") && jRadioRC.isSelected()) JOptionPane.showMessageDialog(null, "Zadajte rodné číslo !");     
        else if(meno.equalsIgnoreCase("") && priezvisko.equalsIgnoreCase("") && jRadioMenoPriezvisko.isSelected()) JOptionPane.showMessageDialog(null, "Zadajte meno a priezvisko !");
        else dispose();
    }//GEN-LAST:event_jButtonHladajActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButtonHladaj;
    private javax.swing.JLabel jLabelMeno;
    private javax.swing.JLabel jLabelPriezvisko;
    private javax.swing.JLabel jLabelRC;
    private javax.swing.JRadioButton jRadioMenoPriezvisko;
    private javax.swing.JRadioButton jRadioRC;
    private javax.swing.JTextField jTextFieldMeno;
    private javax.swing.JTextField jTextFieldPriez;
    private javax.swing.JTextField jTextFieldRC;
    // End of variables declaration//GEN-END:variables
}
