/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import javax.swing.JOptionPane;
import letisko.Kapitan;
/**
 * Dialog pre pridanie kapitana.
 * @author Jakub Cachovan
 */
public class KapitanJDialog extends javax.swing.JDialog {

    private Kapitan kapitan = null;
    /**
     * Creates new form KapitanJDialog
     */
    public KapitanJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * Getter pre objekt typu Kapitan.
     * @return 
     */
    public Kapitan getKapitan(){
        return kapitan;
    }
    
    /**
     * Metóda pre validáciu polí.
     * @return 
     */
    public boolean validacia(){
        if(jTextMeno.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Nie je zadané meno kapitána");
            return false;
        }else if(jTextPriezvisko.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Nie je zadané priezvisko kapitána");
            return false;
        }else if(jTextNalietaneHod.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Nie sú zadané nalietané hodiny kapitána");
            return false;
        }else if(jTextRC.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Nie je zadané rodné číslo kapitána");
            return false;
        }
        return true;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextMeno = new javax.swing.JTextField();
        jTextPriezvisko = new javax.swing.JTextField();
        jTextRC = new javax.swing.JTextField();
        jTextNalietaneHod = new javax.swing.JTextField();
        jButtonUlozitKapitana = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pridanie kapitána");

        jLabel1.setText("Meno");

        jLabel2.setText("Priezvisko");

        jLabel3.setText("Rodné číslo");

        jLabel4.setText("Nalietané hodiny");

        jButtonUlozitKapitana.setText("Uložiť");
        jButtonUlozitKapitana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUlozitKapitanaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextMeno, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextPriezvisko)
                    .addComponent(jButtonUlozitKapitana, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextNalietaneHod)
                    .addComponent(jTextRC)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextMeno, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextPriezvisko, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextRC, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextNalietaneHod, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonUlozitKapitana, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Vytvorenie inštancie kapitána a zrušenie dialogu.
     * @param evt 
     */
    private void jButtonUlozitKapitanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUlozitKapitanaActionPerformed
        /* pridaj kapitana */
        if(validacia()){
            kapitan = new Kapitan(Integer.parseInt(jTextNalietaneHod.getText()), jTextMeno.getText(), jTextPriezvisko.getText(), jTextRC.getText());
            dispose();
        }
    }//GEN-LAST:event_jButtonUlozitKapitanaActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonUlozitKapitana;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextMeno;
    private javax.swing.JTextField jTextNalietaneHod;
    private javax.swing.JTextField jTextPriezvisko;
    private javax.swing.JTextField jTextRC;
    // End of variables declaration//GEN-END:variables
}
